export function handleException(e: any) {
	console.error(e)
}
